spring:
  cassandra:
    keyspace-name: test_audit_keyspace
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
  embedded:
    enabled: true
    startup-timeout: 30s
    persistent: false