spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-test-group
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: audit_keyspace_test
    local-datacenter: dc1
    schema-action: create_if_not_exists

topic:
  audit: test-topic

logging:
  level:
    org.tursunkulov: DEBUG
